<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>default</LangVersion>
    <UltrakillDir>F:/Steam/steamapps/common/ULTRAKILL - Bepinex/</UltrakillDir>
    <PublicizeAll>true</PublicizeAll>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(UltrakillDir)ULTRAKILL_Data/Managed/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="UnityEngine.Modules" Version="2022.3.28" IncludeAssets="compile" />
    <PackageReference Include="Krafs.Publicizer" Version="2.3.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <!-- <Target Name="CopyIntoRude" AfterTargets="Build">
    <Copy SourceFiles="bin/Debug/netstandard2.1/UltraScape.API.dll"
          DestinationFolder="F:/RudeLE17D4/Rude/Assets/BlaixenU/Mods/Nullscape">
    </Copy>
  </Target> -->

  <ItemGroup>
    <SourceFilesToCopy Include="Enemies/Baby.cs"></SourceFilesToCopy>
    <SourceFilesToCopy Include="Enemies/BabyTrail.cs"></SourceFilesToCopy>
  </ItemGroup>

  <Target Name="CopySourceIntoRude" AfterTargets="Build">
    <Copy SourceFiles="@(SourceFilesToCopy)"
          DestinationFolder="F:/RudeLE17D4/Rude/Assets/BlaixenU/Mods/Nullscape/asmdef">
    </Copy>
  </Target>

</Project>
