<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>default</LangVersion>
    <UltrakillDir>F:/Steam/steamapps/common/ULTRAKILL - Bepinex/</UltrakillDir>
    <ModDir>$(UltrakillDir)BepInEx/plugins/UltraScape/</ModDir>
    <PublicizeAll>true</PublicizeAll>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="UnityEngine.Modules" Version="2022.3.28" IncludeAssets="compile" />
    <PackageReference Include="Krafs.Publicizer" Version="2.3.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  
  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(UltrakillDir)ULTRAKILL_Data/Managed/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(UltrakillDir)BepInEx/core/0Harmony.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(UltrakillDir)BepInEx/core/BepInEx.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.Addressables">
      <HintPath>$(UltrakillDir)ULTRAKILL_Data/Managed/Unity.Addressables.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.ResourceManager">
      <HintPath>$(UltrakillDir)ULTRAKILL_Data/Managed/Unity.ResourceManager.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../UltraScape.API/UltraScape.API.csproj" />
  </ItemGroup>

  <Target Name="CopyIntoULTRAKILL" AfterTargets="Build">
    <Copy SourceFiles="bin/Debug/netstandard2.1/UltraScape.dll"
          DestinationFolder="$(ModDir)">
    </Copy>
    <Copy SourceFiles="../Assets/ultrascape"
          DestinationFolder="$(ModDir)">
    </Copy>
  </Target>

  <ItemGroup>
    <Compile Include="../UltraScape.API/Enemies/**/*.cs"></Compile>
  </ItemGroup>
  
  <ItemGroup>
    <DoNotPublicize Include="UnityEngine.CoreModule:UnityEngine.SceneManagement.SceneManager.sceneLoaded" />
  </ItemGroup>
</Project>
